### ISSUE TITLE
Formula for ADMM Image Denosing

### ISSUE THREAD

**Issue by Zeqiang-Lai** [tarmiziAdam2005/Image-Signal-Processing#1]
I am confused about the x update step in admm 2d tv denosing.
What papers did you refer to when you wrote the code? I don't understand why it is wrote that way

I am new to ADMM, and any help would be appreciated

```matlab
    x_old = x;
    rhs = y - rho*Dt(y1/rho + v1, y2/rho + v2);
    lhs = 1 + rho*(eigDtD);
    
    x = fft2(rhs)./lhs;
    x = real(ifft2(x));
    
```

ADMM Image Denoising/ADMM.m

**Comment by tarmiziAdam2005** [comment]
Have you manage to understand the code ?

**Comment by Zeqiang-Lai** [comment]
> Have you manage to understand the code ?

no, I thought I understood(so I closed the issue), but I actually didn't😂

After reading a lot of material and papers, I found this slide. Is this the mathematics behind the code?  If it is, could you give me a little more explanation?  

- D is a convolution filter right? but what does D^T means? And why D^TD is computed in the following way?

```
eigDtD  = abs(fft2([1 -1], row, col)).^2 + abs(fft2([1 -1]', row, col)).^2;
``` 

I try to replace the computation of eigDtD  with this snippet, but the result is not as good as the original one, what is the difference between these computation?

```
eig = abs(fft2([2 -1;-1 0], row,col)).^2;
```

![image](https://user-images.githubusercontent.com/26198430/102970332-4e57f280-4532-11eb-831f-4ed24dbda7fc.png)

Besides:

if this equation hold? 
```
fft(1+rho*D^TD) = 1 + rho*(eigDtD);
```

**Comment by tarmiziAdam2005** [comment]
In the code, the x sub-problem (linear system) is purely solved in the frequency domain because it is fast. 

Yes, D is a convolution. Dt is its transpose. 

eigDtD is the operator DtD in the frequency domain. This is because we want to solve the linear system in the frequency domain.  We precompute DtD before the main loop to save CPU time.

This,

`eigDtD  = abs(fft2([1 -1], row, col)).^2 + abs(fft2([1 -1]', row, col)).^2;`

is computing DtD in frequency domain for both the horizontal and vertical difference operator.

**Comment by tarmiziAdam2005** [comment]
From the notes you give above, solving theta is exactly what we are doing for the x-subproblem in the code.

solving theta is solving linear system Ax = b.

A is the inverse (I + rho*DtD)^-1 and x the vector ( y + rho Dt(.....) ) and b is theta.

We know that convolution in the time domain (spatial domain) is equal to multiplication in the frequency domain, that is why we use ffts to solve this linear system in frequency domain.


hope this helps....

**Comment by Zeqiang-Lai** [comment]
After two days of learning and testing, I finally understood what happens behind the code. Thanks for your help!

From what I have learnt, I implemented the ForwardDiff and Dive in a slightly different way:
```matlab
function [Dux,Duy] = ForwardDiff(U)
 Dux = [U(:,1,:) - U(:,end,:), diff(U,1,2)];
 Duy = [U(1,:,:) - U(end,:,:); diff(U,1,1)];
end

function DtXY = Dive(X,Y)
  % Transpose of the forward finite difference operator
  % is the divergence fo the forward finite difference operator
  DtXY = [-diff(X,1,2), X(:,end) - X(:, 1)];
  DtXY = DtXY + [-diff(Y,1,1); Y(end,:) - Y(1, :)];   
end
```

where the origin one is:
```matlab
function [Dux,Duy] = ForwardDiff(U)
 Dux = [diff(U,1,2), U(:,1,:) - U(:,end,:)];
 Duy = [diff(U,1,1); U(1,:,:) - U(end,:,:)];
end

function DtXY = Dive(X,Y)
  % Transpose of the forward finite difference operator
  % is the divergence fo the forward finite difference operator
  DtXY = [X(:,end) - X(:, 1), -diff(X,1,2)];
  DtXY = DtXY + [Y(end,:) - Y(1, :); -diff(Y,1,1)];   
end
```

Both versions work, but I don't know why.

In case someone else has the same problem as me, I wrote a post explaining the keypoint of the code. See [2D TV Denosing with ADMM -- Mathematics && Implementation](https://zeqiang-lai.github.io/blog/en/posts/admm-2d-tv/)
